apiVersion: platform.glueops.dev/v1alpha1
kind: Gate
metadata:
  name: some-name-prod
  namespace: nonprod
spec:
  checks:
    - id: postgres
      deploymentAvailable:
        name: some-name
        minAvailableReplicas: 1
